"cloopm": "Cloopm"
# organization
"cloopm.global-reports": "Global Reports"
"cloopm.issue-type": "Issue Type"
"cloopm.issue-type-schemes": "Issue Type Schemes"
"cloopm.state-machine-schemes": "StateMachine Schemes"
"cloopm.screens": "Screens"
"cloopm.screen-schemes": "Screen Schemes"
"cloopm.issue-type-screen-schemes": "Issue Type Screen Schemes"
"cloopm.custom-fields": "Custom Fields"
"cloopm.field-configurations": "Field Configurations"
"cloopm.field-configuration-schemes": "Field Configuration Schemes"
"cloopm.priorities": "Priorities"
"cloopm.notification-schemes": "Notification Schemes"
"cloopm.users": "Users"
