"issue": "Issue"
# organization
"issue.global-reports": "Global Reports"
"issue.issue-type": "Issue Type"
"issue.issue-type-schemes": "Issue Type Schemes"
"issue.state-machine-schemes": "StateMachine Schemes"
"issue.screens": "Screens"
"issue.screen-schemes": "Screen Schemes"
"issue.issue-type-screen-schemes": "Issue Type Screen Schemes"
"issue.custom-fields": "Custom Fields"
"issue.field-configurations": "Field Configurations"
"issue.field-configuration-schemes": "Field Configuration Schemes"
"issue.priorities": "Priorities"
"issue.notification-schemes": "Notification Schemes"
