"cloopm": "运维管理"
# organization
"cloopm.global-reports": "报表"
"cloopm.issue-type": "问题类型"
"cloopm.issue-type-schemes": "问题类型方案"
"cloopm.state-machine-schemes": "状态机方案"
"cloopm.screens": "页面"
"cloopm.screen-schemes": "页面方案"
"cloopm.issue-type-screen-schemes": "问题类型页面方案"
"cloopm.custom-fields": "自定义字段"
"cloopm.field-configurations": "字段配置"
"cloopm.field-configuration-schemes": "字段配置方案"
"cloopm.priorities": "优先级"
"cloopm.notification-schemes": "通知方案"
"cloopm.users": "用户"
