"issue": "问题管理"
# organization
"issue.global-reports": "报表"
"issue.issue-type": "问题类型"
"issue.issue-type-schemes": "问题类型方案"
"issue.state-machine-schemes": "状态机方案"
"issue.screens": "页面"
"issue.screen-schemes": "页面方案"
"issue.issue-type-screen-schemes": "问题类型页面方案"
"issue.custom-fields": "自定义字段"
"issue.field-configurations": "字段配置"
"issue.field-configuration-schemes": "字段配置方案"
"issue.priorities": "优先级"
"issue.notification-schemes": "通知方案"
